### ISSUE TITLE
No apt cli works

### ISSUE THREAD

**Issue by gilbertoferreira** [zorbathut/dosvob#1]
Can you help?
ssh -o StrictHostKeyChecking=no root@IP apt install rsync
Warning: Permanently added 'IP' (ED25519) to the list of known hosts.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Error! Cleaning up before returning.
droplets GET {'tag_name': 'dosvob-ephemeral', 'per_page': 200}
droplets/367206744 DELETE {}
snapshots GET {'per_page': 200}
volumes GET {'per_page': 200}
account/keys GET {'per_page': 200}
account/keys/38958166 DELETE {}
Traceback (most recent call last):
  File "/home/user/dosvob/dosvob.py", line 88, in <module>
    execute(f"ssh -o StrictHostKeyChecking=no root@{workerip} apt install rsync")
  File "/home/user/dosvob/dosvob.py", line 57, in execute
raise RuntimeError
RuntimeError

**Comment by zorbathut** [comment]
Whoa, someone else using this? Wild.

I'm actually not sure what's going on there. It sounds like the image might be in the process of doing its own apt update, and now I'm curious why mine *haven't* been doing that (I just checked my logs; they haven't.) Either that, or for some reason it's using an image that requires root, though I think `apt` is good at diagnosing that, so that probably isn't it.

If you can figure out what's going on I'm happy to fix it, but I honestly don't know how that can happen.

**Comment by gilbertoferreira** [comment]
Well other thing that it's doing bad: it's take over IP another than its has in droplet!
So weird.

**Comment by gilbertoferreira** [comment]
For now, I will use dd to create a image.
But using your software could be a handy.
